### ISSUE TITLE
[L2T] Generate Annotation for Evosuite Evaluation

### ISSUE THREAD

**Issue by llmhyy** [sunjun-group/Ziyuan#103]
Given the information provided by @lylytran , we can optimize evosuite evaluation with following steps:
1. We scan the project to get a list of valid methods (the code has already exist in project)
2. We generate evosuite @include and @exclude annotation for them.
3. Then, we can run evosuite to generate test cases and let Ziyuan to collect coverage information for each of them.

**Comment by lylytran** [comment]
finished at commit f24b489a7acec72e89e8c50265a92234cf6fce84
usage: configure target methods in either txt file or let evosuite read from our exported excel
- for Math project: 
configure for the run in apache-commons-math.properties
add libs folder in math project which contains evosuite-*.jar, junit.jar (can be found in evosuite/src/test/resources)
run evosuite.MathEvosuiteTest.runMathProjectExcel() or evosuite.MathEvosuiteTest.runMathProjectTxt()
In case of running by excel: 2 new column will be added next to last existing cols: evosuite coverage (branch coverage), and evosuite coverage info

**Comment by llmhyy** [comment]
That's great!

Can I ask how to distinguish synonym method by current excel format? Do we need to enhance the format of the excel?

**Comment by lylytran** [comment]
the method will be determined by both method name and start line number, and we donnot need to change the format of excel.
The idea is that EvosuiteEvaluation will read the excel by matching title name, so just make sure we don't change the header name of column MethodName and StartLineNumber

**Comment by llmhyy** [comment]
Thanks! But you can generate the excel of those valid methods from Math to have a try to see whether it works.
