### ISSUE TITLE
[L2T] Coverage Calculation Bug

### ISSUE THREAD

**Issue by llmhyy** [sunjun-group/Ziyuan#123]
Hi Lyly, 

Would you please check the function: org.apache.commons.math.distribution.PascalDistributionImpl.inverseCumulativeProbability.203?

Evosuite seems to reach 100% coverage, but Ziyuan only reports 75% coverage. Please kindly have a check.

**Comment by lylytran** [comment]
looks like it's fixed at rev. 4c43d61
