### ISSUE TITLE
[Configuration] Jar File Version

### ISSUE THREAD

**Issue by llmhyy** [sunjun-group/Ziyuan#145]
hi @lylytran 

I find that the jar compilation code does not for the jdk version above 1.8.0_151. The version on the server is 1.8.0_131. In newer version, there is no jar.exe file in jdk any more. Would you please check the issue and update the code? Many thanks!

**Comment by lylytran** [comment]
it's weir, the version I use is 1.8.0_171, and there is jar.exe in bin folder

**Comment by llmhyy** [comment]
thanks lyly, the
