### ISSUE TITLE
Incorrect Fitness Function

### ISSUE THREAD

**Issue by llmhyy** [sunjun-group/Ziyuan#146]
hi @lylytran 

Given the following code, the when a=1000, b=1, its fitness function to line 1 is 0.  I checked the problem in `conditionVariationMap` of the input. Would you please kindly have a check? Moreover, can you show me the code where you define the fitness in instrumentation code? Thanks!

```
0      public int test(int a, int b){
1		if(isValid(a, b)){
2			if(Math.abs(a-b)>=9){
3				return 0;
4			}
5		}
6		
7		return 1;
8	}
```

**Comment by lylytran** [comment]
hi Lin Yun,
Please correct me if I did it wrong. For the code above, at line one, or particularly, at condition node if, the fitness function in the case of line 1 is not of (a, b) but of isValid() function and 0, so we will only have 0/1 result which is corresponding to only true/false value of function isValid().
The fitness is defined in CoverageTracer._onIf...() function.
