### ISSUE TITLE
[L2T] Accomplish the Regression Test Mechanism Based on Excel File

### ISSUE THREAD

**Issue by llmhyy** [sunjun-group/Ziyuan#36]
Once the batch evaluation is done, we need to compare the old version of results (an excel file) and the new results. The comparison include:
1. Whether we support new methods or fail to support old methods;
2. Whether the coverage of L2T approach is increased or decreased;
3. Whether more/less methods present the advantage of L2T over randoop;

We shall debug when bad news happens.

**Comment by lylytran** [comment]
impl in the commit 
https://github.com/sunjun-group/Ziyuan/commit/20b62d5ab026e0a1cbfa9b2c0316e2e9f499dbdc
