### ISSUE TITLE
[L2T] Support Frequency of Code Coverage

### ISSUE THREAD

**Issue by llmhyy** [sunjun-group/Ziyuan#41]
Write new instrumentation code to support recording the reaching frequency of an instruction. This function serves as a basic for many following services.

Done by April, 25?

**Comment by lylytran** [comment]
done at commit a9140c55719a1c1ef6e31486b3510dee4f2d2930

**Comment by lylytran** [comment]
done at [commit](https://github.com/sunjun-group/jacoco/commit/a9140c55719a1c1ef6e31486b3510dee4f2d2930)

**Comment by lylytran** [comment]
Done at commit [a9140c55719a1c1ef6e31486b3510dee4f2d2930](https://github.com/sunjun-group/jacoco/commit/a9140c55719a1c1ef6e31486b3510dee4f2d2930)
