### ISSUE TITLE
[L2T] Change of Instrumentation 

### ISSUE THREAD

**Issue by llmhyy** [sunjun-group/Ziyuan#45]
Based on current instrumentation of a test case, we need to additionally do the following two things:
1. let the test case call a method which set the variable values according to data points;
2. add an outside loop so that we do not need to generate and compile too many test cases.

Therefore, given a method like:
```
m(){
    doSomething();
}
```

Our instrumentation should result in the following method with input of a list like `List<DataPoint>`:
```
m'(){
   for each datapoint in list
        initializeVar(datapoint);
        doSomething();
}
```

Shall we make it done before May 8? @lylytran

**Comment by lylytran** [comment]
Let me confirm to make sure that I understand correctly.
- by Datapoint, you mean assignment list in SelectiveSampling, right?
- so, we will use jacoco to collect codecoverage right? that means we only need to run debugger to collect input data once at the beginning and the code in selective sampling which call jvm will be replace with jacoco?
- by instrumentation, will we generate new testcases based on selective samples with the format of code as mentioned above or will we instrument current testcase at running time?

**Comment by llmhyy** [comment]
done
