### ISSUE TITLE
LoopHeader is labeled incorrectly

### ISSUE THREAD

**Issue by ZhangHarry** [sunjun-group/Ziyuan#77]
For org.apache.commons.math.linear.ArrayRealVector.add.261,
DecisionNode 268 should be loop header while DecisionNode 269 is labeled as loop header

[ArrayRealVector.zip](https://github.com/sunjun-group/Ziyuan/files/1236145/ArrayRealVector.zip)

**Comment by lylytran** [comment]
Hi Hairui,
actually, in your case, as in the byte code, the loopheader should be condition node at line 269. 
The logic is that the later condition plays both two roles of a loopheader that are enter and exit the loop while the former condition only play the role of exit loop not enter the loop. That means even if cond1 is executed and satisfied, whether or not the loop is entered based on the cond2, so cond2 is considered as a loopheader

**Comment by ZhangHarry** [comment]
@lylytran 
Hi Lyly,
I think that is confusing, cond2 is not in loop body, but it can be regarded as a part of the entire loop, and then cond1 will also play the role of enter the loop. In this way, cond1 is the head of a 'circle' in CFG, which is more clear.  Would you please modify it when you are free? It is kind of low priority now.

**Comment by lylytran** [comment]
ok, I agree that it might makes more sense if we consider cond1 as loopheader instead of cond2. I'll check it later.
