### ISSUE TITLE
[L2T] Random Target Method Generation

### ISSUE THREAD

**Issue by llmhyy** [sunjun-group/Ziyuan#79]
Problem: Open source methods have a lot of restrictions like assertion, constuctor, global variable without setter methods, too simple methods
General Goal: Generate random methods. (1. without loop; 2. contain some loop)
Criteria
1. only parameters are used, no fields, not global static variable, etc.
2. there should be some nested condition
3. we should randomly generate mathod invocation like Math.max(), Math.abs(), ... in condition

Parameter for method generation: 
1. number of variables, e.g., x, y, ...
2. number of layer for nested condition. if(){if(){if(){...}}}
if(){
	if(){
		if(){
			...
		}
	}
}

For simplicity, we can have static method.

A trick is that, we generate as many as variables, then we use separate variables on different conidtions.

3*. number of loop inside (alter: we may generate dead loop)

Challenge and Open Question:
1. We need an API pool:
At the very beginning, we can use the methods in java.lang.Math. 
We can only pick up the methods with int/double/... return type.

2. How to synthesize the condition:
We may need to use some operators like <, >, ==, <=, or >=.

**Comment by lylytran** [comment]
these are a few thousand generated methods for Math:
[generated methods-Math.zip](https://github.com/sunjun-group/Ziyuan/files/1241164/generated.methods-Math.zip)

**Comment by llmhyy** [comment]
That's great, we will provide the feedback asap.
