### ISSUE TITLE
[L2T] field initialization

### ISSUE THREAD

**Issue by ZhangHarry** [sunjun-group/Ziyuan#84]
Sometimes in method under testing, fields may have not been initialized,  please ensure all related variables in method under testing should be set.

In org.apache.commons.math.estimation.LevenbergMarquardtEstimator.determineLMParameter.164, there are many field without initialization

**Comment by lylytran** [comment]
Hi Hairui, assigning null for a variable is a part of gentest's idea. Of course, we set a reasonable probability for that special value to happen, but we cannot totally exclude that case. 
I have check the method org.apache.commons.math.estimation.LevenbergMarquardtEstimator.determineLMParameter.502, they are all double or double[], so I guess double[] value can be null sometimes, but would not be so frequently.
Let me know if I miss something. In above description, you mentioned fields, not method parameters? do you really mean fields of the method's receiver or just method parameters?
