### ISSUE TITLE
[GAN-Testing] Refactoring for Integrating GAN

### ISSUE THREAD

**Issue by llmhyy** [sunjun-group/Ziyuan#96]
Hi @lylytran,

Would you please kindly create a branch named "gan-testing"? We are trying to integrate GAN (a neural network) to replace SVM and active learning to improve the test coverage. I think we need to refactor Ziyuan to architecturally support both SVM&ActiveLearning and GAN.

I think some code review is necessary before the refactoring. Let's discuss more about it next week. 

@pxzhang94 @joelowj You may also help to discuss the interface between GAN and Ziyuan.

**Comment by lylytran** [comment]
the new branch is named as gan-testing-temp
