### ISSUE TITLE
[GAN-testing] Java-Python Communication and Data Format Definition

### ISSUE THREAD

**Issue by llmhyy** [sunjun-group/Ziyuan#99]
Hi @lylytran ,

Please kindly write a demo of make Java code (Client) communicate with Python code (Server) by Socket. In addition, you may also kindly help define the data format. Thanks a lot!

**Comment by llmhyy** [comment]
I personally suggest to use json format, as there are sufficient library to parse. Anyway, it;s your call to use whatever the technique you like.

**Comment by llmhyy** [comment]
As we discussed today, the major communications are TRAIN and GENERATE. 

For TRAIN command, it follows the content of: (1) decision_node_id and (2) a set of data points
For GENERATE command, it follows the content of: (1) decision_node_id and (2) a label of TRUE/FALSE

In Python code, it shall maintain and track each decision node with a model.

**Comment by lylytran** [comment]
ac935f7a5b59087796fcd091e761853dfdc05176
